CREATE TABLE FMStats (
    ID SERIAL PRIMARY KEY,
    Rec VARCHAR(255),
    Inf VARCHAR(255),
    Name VARCHAR(255),
    Position VARCHAR(255),
    Club VARCHAR(255),
    "On Loan From" VARCHAR(255),
    Based VARCHAR(255),
    "Asking Price" VARCHAR(255),
    Salary VARCHAR(255),
    Expires DATE,
    Nat VARCHAR(50),
    "2nd Nat" VARCHAR(50),
    Height VARCHAR(255),
    Weight VARCHAR(255),
    "Preferred Foot" VARCHAR(255),
    Age INT,
    "Transfer Value" VARCHAR(255),
    Apps VARCHAR(255),
    Starts INT,
    Mins INT,
    "Mins/Gm" DECIMAL(6, 2),
    "Av Rat" DECIMAL(10,2),
    Gls INT,
    "Gls/90" DECIMAL(10,2),
    Shots INT,
    "ShT" INT,
    "Shot %" VARCHAR(255),
    "Shot/90" DECIMAL(10,2),
    "ShT/90" DECIMAL(10,2),
    Pens INT,
    "Pens S" INT,
    "Pen/R" VARCHAR(255),
    Off INT,
    xG DECIMAL(10,2),
    CCC INT,
    "Ch C/90" DECIMAL(10,2),
    Ast INT,
    "Asts/90" DECIMAL(10,2),
    "K Pas" INT,
    "K Ps/90" DECIMAL(10,2),
    "Pas A" INT,
    "Ps A/90" DECIMAL(10,2),
    "Ps C" INT,
    "Ps C/90" DECIMAL(10,2),
    "Pas %" VARCHAR(255),
    "Cr A" INT,
    "Cr C" INT,
    "Cr C/A" VARCHAR(255),
    Drb INT,
    "Drb/90" DECIMAL(10,2),
    FA INT,
    Distance VARCHAR(255),
    "Hdrs A" INT,
    "Aer A/90" DECIMAL(10,2),
    Hdrs INT,
    "Hdrs W/90" DECIMAL(10,2),
    "Hdr %" VARCHAR(255),
    "K Tck" INT,
    "Tck W" INT,
    "Tck" DECIMAL(10,2),
    "Tck R" DECIMAL(10,2),
    Fls INT,
    Yel INT,
    Red INT,
    Itc INT,
    "Int/90" DECIMAL(10,2),
    Clear INT,
    Conc INT,
    "All/90" DECIMAL(10,2),
    Shutouts INT,
    "xSv %" VARCHAR(255),
    Svh INT,
    Svt INT,
    Svp INT,
    "Sv %" VARCHAR(255),
    "Pens Faced" INT,
    "Pens Saved" INT,
    "Pens Saved Ratio" VARCHAR(255)
);
